name: Deploy to Heroku

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Push to Heroku
      run: git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git origin/master:master